Selenium server request timeout
2gis/vmmaster pull request #198
Opened 2017-03-16 13:07 UTC by sh0ked

2017-03-20 05:13 UTC, z00sts requested changes

2017-03-20 05:13 UTC, z00sts commented on vmpool/clone.py
> +        return True if self.get_vm(server_name) else False
Тут можно просто вернуть результат self.get_vm, потому что этот if реально ничего не оборачивает

2017-03-20 05:13 UTC, z00sts commented on vmmaster/api/__init__.py
> +                endpoint.delete(try_to_rebuild=False)
Это уже внутри

2017-03-21 02:56 UTC, skyline-gleb approved these changes
Может не добавлять пока codecov, чтоб не мазолил глаза?))

2017-03-21 08:23 UTC, z00sts commented on tests/run_unittests.py
> -nose.run(defaultTest="unit")
:+1:

2017-03-21 08:33 UTC, z00sts commented on tests/unit/test_server.py
> +        __name__='is_created',
` __name__='is_created'`
Вот эти штуки по мне больше отвлекают от сути теста и дают мало пользы, но их у нас много и на твоё усмотрение.

2017-03-21 08:35 UTC, z00sts commented on vmmaster/api/__init__.py
> +            results.append(endpoint.name)
А почему здесь перешли от хранения самих обьектов к хранению имен?

2017-03-21 08:51 UTC, z00sts commented on vmpool/clone.py
> -
Больше не делаем несколько попыток пропинговать и сребилдить?

2017-03-21 08:58 UTC, z00sts commented on vmpool/clone.py
>                  time.sleep(config_create_check_pause)
Вроде как эта паузка должна быть за пределами этого if по хорошему.

2017-03-21 09:01 UTC, z00sts commented on vmpool/clone.py
> +            return server if server.name == server_name else None
Какая-то странная проверка на имя, не находишь? Или в ней есть смысл?

2017-03-21 09:10 UTC, z00sts requested changes

2017-03-21 09:10 UTC, z00sts commented on vmpool/clone.py
> +            elif self.is_created(server):
Дико не нравится server в качестве параметра у этих методов, но решение только такое: при получении сервера выше нужно его положить в self.server обьекта и тогда эти методы будут не static и без параметров. Что думаешь?

2017-03-21 09:10 UTC, sh0ked commented on tests/unit/test_server.py
> +        __name__='is_created',
да я бы это все убрал, но не стал сейчас менять сильно, просто изменил название метода, потом все вычистив по тестам

2017-03-21 09:12 UTC, sh0ked commented on vmmaster/api/__init__.py
> +            results.append(endpoint.name)
Потому что ты получаешь ответ от апи, когда очистил пул, а тебе возвращается "deleted [<OpenstackClone>, <OpenstackClone>]" и нафиг оно надо, ниче же непонятно

2017-03-21 09:14 UTC, z00sts commented on vmmaster/api/__init__.py
> +            results.append(endpoint.name)
Нет вопросов.

2017-03-21 09:14 UTC, sh0ked commented on vmpool/clone.py
> -
этот код не работал =D 
ребилд делается на уровне выше, тут он излишний

2017-03-21 09:17 UTC, sh0ked commented on vmpool/clone.py
> +            elif self.is_created(server):
Да, сейчас так пусть остается. То о чем ты говоришь сделано в DockerClone, а потом перекочует подход в OpenstackClone. Сейчас вот так это некоторый компромисс, ну и на будущее задел под переделку

2017-03-21 09:17 UTC, z00sts commented on vmpool/clone.py
> +            elif self.is_created(server):
Нет вопросов.

2017-03-21 09:17 UTC, z00sts commented on vmpool/clone.py
> -
Нет вопросов.

2017-03-21 09:18 UTC, z00sts commented on tests/unit/test_server.py
> +        __name__='is_created',
:+1:

2017-03-21 09:18 UTC, sh0ked commented on vmpool/clone.py
>                  time.sleep(config_create_check_pause)
Почему? Пауза как раз нужна только в момент создания пока виртуалка в build/rebuild статусе

2017-03-21 09:20 UTC, sh0ked commented on vmpool/clone.py
> +            return server if server.name == server_name else None
Пожалуй, но это просто как есть перенесено. Потом будет перепиливаться OpenstackClone. Можно сейчас убрать, если прям критично?

2017-03-21 09:20 UTC, z00sts commented on vmpool/clone.py
>                  time.sleep(config_create_check_pause)
Точно, :+1:

2017-03-21 09:23 UTC, z00sts commented on vmpool/clone.py
> +            return server if server.name == server_name else None
Давай уберем и, если всё ок, вливаем?

2017-03-21 09:23 UTC, sh0ked commented on vmpool/clone.py
> +            return server if server.name == server_name else None
Давай

2017-03-21 09:39 UTC, sh0ked commented on vmpool/clone.py
> +            return server if server.name == server_name else None
Все

2017-03-21 09:41 UTC, z00sts approved these changes

2017-03-21 11:38 UTC, merged