[WIP] Docker provider
2gis/vmmaster pull request #200
Opened 2017-03-22 11:48 UTC by sh0ked

2017-07-19 05:45 UTC, z00sts requested changes

2017-07-19 05:45 UTC, z00sts commented on core/utils/__init__.py
> +            log.exception("Error")
На всякий случай подмечу, что *вернёт None* в случае except (!). Можно параметризовать этот декоратор, чтобы возвращал кастомное значение при exception

2017-07-19 05:45 UTC, z00sts commented on core/sessions.py
> +        self.vnc_helper.start_recording(size=config.SCREENCAST_RESOLUTION)
Думаю, `size=config.SCREENCAST_RESOLUTION` тоже должно заехать в конструктор VNCVideoHelper

2017-07-19 05:45 UTC, z00sts commented on core/utils/network_utils.py
> +            queue.put(e)
Давай вынесем get_response из make_request

2017-07-19 05:45 UTC, z00sts commented on vmmaster/webdriver/commands.py
> +        request, session, session.endpoint.selenium_port
Ты уже сессию туда пробрасываешь, пусть он сам из неё и достает `.endpoint.selenium_port / ports`

2017-07-19 05:45 UTC, z00sts commented on vmmaster/webdriver/helpers.py
> +        for screenshot in commands.take_screenshot(session, session.endpoint.agent_port):
Тут тоже давай только сессию пробрасывать?

2017-07-19 05:45 UTC, z00sts commented on vmmaster/webdriver/helpers.py
> +        request.session.endpoint.selenium_port,
1) А почему вобще пришлось перестать использовать SELENIUM_PORT из конфига?
2) Может для request сделать property-обёртку, которая будет отдавать session.endpoint.selenium_port?

2017-07-19 05:45 UTC, z00sts commented on vmpool/artifact_collector.py
> +    session.endpoint = endpoint
Что-то странное, у неё уже должен быть endpoint в этот момент, не нужно его пробрасывать всюду в collector параметром. Лучше пробрасывать обьект session (весь, а не session_id)

2017-07-19 05:45 UTC, z00sts commented on vmpool/clone.py
> +            return self.container.ports.get(original_port)
Можно в exception_handler тут тоже завернуть, ну и в тех методах ниже, где `self.container`

2017-07-19 05:56 UTC, sh0ked commented on core/utils/__init__.py
> +            log.exception("Error")
Везде где используется декоратор и предполагается, что получим None, вполне ожидаемо

2017-07-19 05:57 UTC, sh0ked commented on core/sessions.py
> +        self.vnc_helper.start_recording(size=config.SCREENCAST_RESOLUTION)
можно да

2017-07-19 06:00 UTC, sh0ked commented on vmmaster/webdriver/commands.py
> +        request, session, session.endpoint.selenium_port
не выйдет пока, я собирался так и сделать. Но мы в artifact collector восстанавливаем сессию из бд, там не присвоено значение endpoint и ничего нет. посмотрю можно ли отказаться от восстановления из бд

2017-07-19 06:15 UTC, sh0ked commented on vmmaster/webdriver/helpers.py
> +        for screenshot in commands.take_screenshot(session, session.endpoint.agent_port):
тут можно только сессию прокидывать

2017-07-19 06:15 UTC, sh0ked commented on vmmaster/webdriver/helpers.py
> +        request.session.endpoint.selenium_port,
1. Все порты на прямую не используются, потому что для dockerprovider selenium port не будет 4455, а будет сгенерен рандомный и замапится на настоящий 4455 внутри контейнера

2017-07-19 06:15 UTC, sh0ked commented on vmmaster/webdriver/helpers.py
> +        request.session.endpoint.selenium_port,
2. Не понял, зачем делать такую обертку? В данном месте нам нужен селениум_порт, его и получаем. тебе не нравится, что есть у endpoint есть property для портов?

2017-07-19 06:15 UTC, sh0ked commented on vmpool/artifact_collector.py
> +    session.endpoint = endpoint
вот строчка выше говорит об обратном. если получится от нее избавиться, тогда можно не прокидывать

2017-07-19 06:15 UTC, sh0ked commented on vmpool/clone.py
> +            return self.container.ports.get(original_port)
зачем? все что в них вызывается обернуто уже в exception_handler, если не обернуто, значит, в тех местах мы должны прям падать, потому что дальше не сможем работать с None

2017-07-19 06:15 UTC, sh0ked commented on core/utils/network_utils.py
> +            queue.put(e)
Лучше отдельным pr

2017-07-19 08:02 UTC, skyline-gleb approved these changes

2017-07-19 08:03 UTC, z00sts commented on core/utils/__init__.py
> +            log.exception("Error")
Ок, просто где-то может приводить к ошибкам, где не будет ожидаться None

2017-07-19 08:04 UTC, z00sts commented on vmmaster/webdriver/commands.py
> +        request, session, session.endpoint.selenium_port
Полюбому можно! Мы на момент, когда начинаем сохранять артефакты для сессии, имеем этот обьект сессии в наличии?

2017-07-19 08:17 UTC, z00sts commented on vmmaster/webdriver/helpers.py
> +        request.session.endpoint.selenium_port,
1. Понял
2. Мне не нравится, когда из реквеста распаковываем всё вплоть до endpoint

2017-07-19 08:32 UTC, z00sts commented on vmpool/clone.py
> +            return self.container.ports.get(original_port)
Понял

2017-07-19 08:50 UTC, sh0ked commented on vmmaster/webdriver/commands.py
> +        request, session, session.endpoint.selenium_port
ой, это про artifact collector было (уже поправил), тут конечно сделаю как ты предложил.

2017-07-19 08:56 UTC, sh0ked commented on core/utils/__init__.py
> +            log.exception("Error")
Ну параметризировать можно, просто другие значения нигде не нужны пока

2017-07-19 08:58 UTC, sh0ked commented on vmmaster/webdriver/helpers.py
> +        request.session.endpoint.selenium_port,
ну это история о том, что у нас все хранится в request. но тут самое место в endpoint хранить порты и получать, они не статичные же

2017-07-19 08:59 UTC, z00sts commented on vmmaster/webdriver/helpers.py
> +        request.session.endpoint.selenium_port,
Ок, это не сильно большая проблема.

2017-07-20 11:55 UTC, sh0ked commented on vmmaster/webdriver/helpers.py
> +        request.session.endpoint.selenium_port,
ok

2017-07-20 12:08 UTC, sh0ked commented on vmmaster/webdriver/helpers.py
> +        request.session.endpoint.selenium_port,
в общем я все поправил что было

2017-07-21 09:33 UTC, z00sts approved these changes

2017-07-23 15:16 UTC, merged