Sessions in db
2gis/vmmaster pull request #221
Opened 2017-08-20 16:27 UTC by sh0ked

2017-08-20 16:28 UTC, sh0ked commented
!test

2017-08-21 05:24 UTC, skyline-gleb approved these changes

2017-08-21 05:47 UTC, z00sts requested changes

2017-08-21 05:47 UTC, z00sts commented on core/sessions.py
> +            raise SessionException("There is no active session {} ({})".format(session_id, reason))
Давай тут нормально перепишем, каша какая-то с if. 

Сразу после получения сессии:
```
if not session:
    raise SessionException
```

2017-08-21 05:47 UTC, z00sts commented on vmpool/__init__.py
> -        dispatcher.send(signal=Signals.DELETE_VIRTUAL_MACHINE, sender=self)
Не помнишь, зачем было нужно изначально?

2017-08-21 05:47 UTC, z00sts commented on core/db/models.py
> +        current_app.database.delete(self)
Мне кажется, delete нам не нужен, т.к. не пользуемся

2017-08-21 05:48 UTC, sh0ked commented on core/db/models.py
> +        current_app.database.delete(self)
не пользуемся, но я добавил, чтобы был и понадобится в ui позже

2017-08-21 05:56 UTC, sh0ked commented on core/sessions.py
> +            raise SessionException("There is no active session {} ({})".format(session_id, reason))
давай, но здесь надо понимать важно сохранить обратную совместимость, то есть даже если сессия закрыта, мы должны откидывать экспешн

2017-08-21 05:56 UTC, sh0ked commented on vmpool/__init__.py
> -        dispatcher.send(signal=Signals.DELETE_VIRTUAL_MACHINE, sender=self)
это легаси, которое никогда не работало

2017-08-21 05:56 UTC, sh0ked commented on vmpool/__init__.py
> -        dispatcher.send(signal=Signals.DELETE_VIRTUAL_MACHINE, sender=self)
по крайней мере, когда мы пришли на проект

2017-08-21 05:57 UTC, z00sts commented on core/sessions.py
> +            raise SessionException("There is no active session {} ({})".format(session_id, reason))
Да, я за. Только лапшу эту причесать

2017-08-21 06:26 UTC, sh0ked commented on core/sessions.py
> +            raise SessionException("There is no active session {} ({})".format(session_id, reason))
так норм?

2017-08-21 06:43 UTC, z00sts commented on core/sessions.py
> +            raise SessionException("There is no active session {} (Unknown session)".format(session_id))
Наверное, лучше стало

2017-08-21 06:44 UTC, z00sts commented
!test

2017-08-21 06:52 UTC, FreakyGranny approved these changes

2017-08-21 06:52 UTC, z00sts approved these changes

2017-08-22 04:03 UTC, merged