[WIP] Endpoints in db
2gis/vmmaster pull request #222
Opened 2017-08-22 12:28 UTC by sh0ked

2017-08-23 09:31 UTC, z00sts requested changes

2017-08-23 09:31 UTC, z00sts commented on core/db/__init__.py
> +            clone = Clone
Это очень некруто выглядит. Давай через DockerPlatforms / OpenstackPlatoforms обращаться, а они уже будут ходить в бд. И возвращать они всегда будут обьекты типа Clone (но конкретизированные до DockerCLone например). О типах этих клонов БД знать не должна.

Метод get_endpoint - аналогично

Если не хочется менять способ, которым щас модель заворачивается в clone - то пусть get_endpoints получает на вход класс, из которого надо сделать обьекты.

2017-08-23 09:31 UTC, z00sts commented on vmmaster/app.py
> +        )
Больше похоже на то, что provider - это пул, значит он сам должен регистрироваться. Раньше регалось всё приложение - это не очень правильно, когда мы оперируем понятиями provider

2017-08-23 09:31 UTC, z00sts commented on vmmaster/app.py
> +            self.sessions.stop_worker()
`stop_workerS` (на самом деле можно это обозвать просто stop я думаю)

2017-08-23 09:31 UTC, z00sts commented on vmmaster/http_proxy.py
> +        host = session.endpoint.ip
Чето не пойму, где это используется

2017-08-23 09:31 UTC, z00sts commented on vmmaster/webdriver/commands.py
> +             % (session.id, session.endpoint.name, session.endpoint.ip))
Давай это вынесем в какой-нибудь `session.__str__` что ли? Когда два раза в глубь обьекта лезем - это надо прятать уже внутрь.

2017-08-23 09:31 UTC, z00sts commented on vmpool/artifact_collector.py
> +    host = "ws://%s:%s/runScript" % (session.endpoint.ip, session.endpoint.agent_port)
1) Называется `get_artifact_from_endpoint` - на вход суем session и достаем из неё endpoint_ip и порт. Нужен только host + port. (`session` передается ради написания сообщения в лог (ниже), это можно сделать там, где вызываем get_artifact_from_endpoint).

2) Давай сделаем у `endpoint` проперти agent_socket (или agent_url), чтобы не клеить это каждый раз.

2017-08-23 09:31 UTC, z00sts commented on vmpool/clone.py
> +    network_name = None
Эти два атрибута нигде не проставляются. Нужны?

2017-08-23 12:16 UTC, sh0ked commented on vmmaster/app.py
> +        )
Да, по сути так и есть. Тут я не стал сразу двигать, но видимо лучшее место это пул. Будет регать себя сам.

2017-08-23 12:18 UTC, sh0ked commented on vmmaster/app.py
> +            self.sessions.stop_worker()
stop_workers пожалуй, но просто stop может путать. Session - это не тред, не воркер, не приложение, а просто объект же

2017-08-23 12:20 UTC, sh0ked commented on vmmaster/http_proxy.py
> +        host = session.endpoint.ip
http_proxy? я уже тоже не уверен, что это вообще работает и используется. Просто теперь у session нет endpoint_ip, а есть endpoint.ip, просто замена. Но ниже оно в reactor прокидывается же

2017-08-23 12:20 UTC, sh0ked commented on vmmaster/webdriver/commands.py
> +             % (session.id, session.endpoint.name, session.endpoint.ip))
👍

2017-08-23 12:22 UTC, sh0ked commented on vmpool/artifact_collector.py
> +    host = "ws://%s:%s/runScript" % (session.endpoint.ip, session.endpoint.agent_port)
опять же просто заменил тут, давай переделаем, давно же можно уже переделать было.

2017-08-23 12:23 UTC, sh0ked commented on vmpool/clone.py
> +    network_name = None
И правда не нужны

2017-08-23 12:24 UTC, sh0ked commented on core/db/__init__.py
> +            clone = Clone
Мне тоже этот момент не нравится вообще, но я пока еще работаю над MR и хотел узнать твое мнение. Давай попробуем твоим вариантом сделать, так конечно оставлять сильно плохо.

2017-08-24 02:34 UTC, z00sts commented on vmmaster/app.py
> +            self.sessions.stop_worker()
да, согласен

2017-08-24 02:34 UTC, z00sts commented on vmmaster/http_proxy.py
> +        host = session.endpoint.ip
неправильно посмотрел, всё понял.

2017-08-24 02:35 UTC, z00sts commented on vmpool/artifact_collector.py
> +    host = "ws://%s:%s/runScript" % (session.endpoint.ip, session.endpoint.agent_port)
да, заметно тут стало, я за "принцип пионера" (http://programmer.97things.oreilly.com/wiki/index.php/The_Boy_Scout_Rule)

2017-08-24 02:37 UTC, z00sts commented on core/db/__init__.py
> +            clone = Clone
У нас был обьект Platforms, который был интерфейсом ко всем платформам. Думаю, его и надо продолжать использовать: он в себе прячет логику "откуда и какую платформу достать" и к БД он тоже обращается. Так проще будет контролировать эти интерфейсы

2017-08-31 12:43 UTC, sh0ked commented
!test

2017-09-01 04:40 UTC, sh0ked commented
!test

2017-09-01 04:48 UTC, sh0ked commented
в интеграционных в мастере сломано 2 теста, починится в #224

2017-09-01 07:49 UTC, sh0ked commented
!test

2017-09-01 10:01 UTC, sh0ked commented
!test

2017-09-01 12:25 UTC, sh0ked commented
!test

2017-09-04 08:01 UTC, z00sts commented on core/db/__init__.py
> +            return dbsession.query(Platform).filter_by(name=name).first()
Можно тут добавить в лог сообщение, что платформа не найдена (если она будет не найдена) и только потом вернуть None (в обоих кейсах if)

2017-09-04 08:01 UTC, z00sts commented on core/db/__init__.py
> +            log.exception("Session %s not found" % session_id)
Тут наверное `log.exception` не нужен, может `log.warning` просто? По трейсбеку всё равно ничего нового не узнаем, скорее всего. Что думаешь?

2017-09-04 08:43 UTC, sh0ked commented on core/db/__init__.py
> +            log.exception("Session %s not found" % session_id)
Да, как-то мне не особо мешает трейс в таком случае, если хочешь давай warning сделаем

2017-09-04 08:43 UTC, sh0ked commented on core/db/__init__.py
> +            return dbsession.query(Platform).filter_by(name=name).first()
ок

2017-09-04 09:56 UTC, sh0ked commented
!test

2017-09-04 09:56 UTC, sh0ked commented on core/db/__init__.py
> +            return dbsession.query(Platform).filter_by(name=name).first()
посмотри, так тебе хотелось?

2017-09-04 12:07 UTC, sh0ked commented
!test

2017-09-04 12:40 UTC, sh0ked commented
!test

2017-09-04 12:51 UTC, sh0ked commented
!test

2017-09-05 03:58 UTC, sh0ked commented
!test

2017-09-05 05:26 UTC, z00sts requested changes

2017-09-05 05:26 UTC, z00sts commented on vmmaster/api/__init__.py
> +    if _session and _session.endpoint.ip and getattr(_session, "endpoint", None):
`_session.endpoint.ip` в конец условия

2017-09-05 05:26 UTC, z00sts commented on core/db/models.py
> +        self.platform_id = self.get_platform_id()
Тут надо переделать на работу с атрибутом `platform` напрямую. С айдишниками явно не работаем.

Как тут:

https://github.com/2gis/vmmaster/blob/657fe90c3df77fa0b8f49e7d6ed36ca9a4f81cd7/core/db/models.py#L127-L141

Будет как-то так:

```python
self.provider = get_provider(provider_name)
self.platform = get_platform(platform_name, provider.id)
```

2017-09-05 05:28 UTC, z00sts commented on core/db/models.py
> +        self.provider_id = provider_id
Тут тоже:
```python
self.provider = get_provider(по id или по name)
```

2017-09-05 05:29 UTC, z00sts commented on core/db/models.py
> +    platform = Column(String, nullable=False)
Можем переименовать пока platform в platform_name?

2017-09-05 05:30 UTC, z00sts commented on core/db/models.py
> +    platform = Column(String, nullable=False)
Вместе с колонкой в БД заодно.

2017-09-05 05:31 UTC, z00sts commented on core/db/models.py
> +        self.platform_id = self.get_platform_id()
Вобще сюда бы круто уже обьект Platform пробрасывать просто

2017-09-05 05:32 UTC, z00sts commented on core/db/models.py
> +        self.provider_id = provider_id
И relationship с провайдером нужен

2017-09-05 05:33 UTC, z00sts commented on core/sessions.py
> +                "name": self.endpoint.name
Здесь хорошо бы спрятать это всё в endpoint.info, который отдает JSON, а мы уже просто приклеиваем его в основной stat

2017-09-05 10:36 UTC, sh0ked commented on core/db/models.py
> +    platform = Column(String, nullable=False)
сделал

2017-09-05 10:36 UTC, sh0ked commented on core/db/models.py
> +        self.platform_id = self.get_platform_id()
сделал

2017-09-05 10:36 UTC, sh0ked commented on core/db/models.py
> +        self.provider_id = provider_id
переделал

2017-09-05 10:36 UTC, sh0ked commented on core/sessions.py
> +                "name": self.endpoint.name
давай потом, уже прям очень много изменений и я боюсь пропустить какаху

2017-09-05 10:36 UTC, sh0ked commented on vmmaster/api/__init__.py
> +    if _session and _session.endpoint.ip and getattr(_session, "endpoint", None):
готово

2017-09-05 10:59 UTC, sh0ked commented
!test

2017-09-05 11:29 UTC, sh0ked commented
!test

2017-09-05 12:30 UTC, sh0ked commented
!test

2017-09-05 13:02 UTC, sh0ked commented
!test

2017-09-06 05:18 UTC, z00sts commented on core/db/models.py
> +
Лучше для провайдера прописать:

```python
platforms = relationship("Platform", backref=backref("provider", single_parent=True))
```

Тогда у Platform можно убрать будет

2017-09-06 05:21 UTC, z00sts commented on core/db/models.py
> +    platform = relationship("Platform", backref="endpoint")
Это неправильно, т.к. на платформу много эндпойнтов ссылается. Это должно уехать в класс Platform:

```python
endpoints = relationship("Endpoint", backref=backref("platform", single_parent=True))
```

2017-09-06 06:10 UTC, z00sts commented on vmpool/clone.py
> +            self.nova_client = self._get_nova_client()
Не понял, от чего эта защита

2017-09-06 06:12 UTC, z00sts commented on vmpool/clone.py
> +        self.name = "p{}-{}-{}".format(pool.id, self.prefix, self.id)
Не уверен, что с self.id будет лучше, чем с uuid4

2017-09-06 06:21 UTC, z00sts commented on vmpool/clone.py
> +        while not self.ready or self.deleted:
Кажется, тут косяк. Должно быть что-то вроде:
```python
while not self.ready and not self.deleted:
```

2017-09-06 06:23 UTC, sh0ked commented on vmpool/clone.py
> +            self.nova_client = self._get_nova_client()
Ниже мы обращаемся к nova_client, сделано как для DockerClone. При восстановлении endpoint клиент не восстановится.

2017-09-06 06:24 UTC, z00sts commented on vmpool/clone.py
> +            self.nova_client = self._get_nova_client()
Почему не восстанавливается nova_client? Ведь мы выполняем init, разве нет?

2017-09-06 06:31 UTC, sh0ked commented on vmpool/clone.py
> +        self.name = "p{}-{}-{}".format(pool.id, self.prefix, self.id)
uuid слишком длинн и не нужно, для DockerClone уж точно. OpenstackClone тоже не особо нужно, различить ты из всеравно сможешь, пихать кучу символов в название уже нет смысла

2017-09-06 06:32 UTC, sh0ked commented on vmpool/clone.py
> +        while not self.ready or self.deleted:
да, пропустил not

2017-09-06 06:36 UTC, sh0ked commented on core/db/models.py
> +
попробовал заменить на platforms и endpoints как ты предлагаешь, но наткнулся на какую-то проблему с числом виртуалок в пуле, это странно

2017-09-06 06:59 UTC, z00sts commented on vmpool/clone.py
> +        self.name = "p{}-{}-{}".format(pool.id, self.prefix, self.id)
ну это кусок хеша, он уникальный хотя бы... С айдишниками можно встрять

2017-09-06 06:59 UTC, z00sts commented on vmpool/clone.py
> +        while not self.ready or self.deleted:
и and (!)

2017-09-13 09:17 UTC, z00sts commented on vmpool/clone.py
> +        self.name = "p{}-{}-{}".format(pool.id, self.prefix, self.id)
И тут ошибка: self.name нужно сформировать до того, как дёргается `super(Clone, self).__init__`. Иначе в БД записываются ендпойнты с пустым именем.

2017-09-19 04:46 UTC, z00sts commented
!test

2017-09-19 05:24 UTC, z00sts commented
!test

2017-09-19 07:47 UTC, z00sts commented
!test

2017-09-19 07:53 UTC, z00sts commented
!test

2017-09-19 08:05 UTC, z00sts commented
!test

2017-09-19 09:01 UTC, z00sts approved these changes

2017-09-19 09:02 UTC, merged