Add keep_forever field for session
2gis/vmmaster pull request #224
Opened 2017-08-28 08:48 UTC by z00sts

2017-08-29 04:16 UTC, z00sts commented
!test

2017-08-29 04:23 UTC, z00sts commented
!test

2017-08-29 04:55 UTC, z00sts commented
!test

2017-08-29 05:40 UTC, z00sts commented
!test

2017-08-29 07:08 UTC, z00sts commented
!test

2017-08-29 11:38 UTC, z00sts commented
!test

2017-08-30 07:56 UTC, sh0ked approved these changes

2017-08-31 11:07 UTC, skyline-gleb requested changes
кажется при удалении нигде `keep_forever` не используется, проверь

2017-08-31 11:07 UTC, skyline-gleb commented on migrations/migrations.py
> +    revision = "250c6848576f"
комментарий не? :)

2017-08-31 11:23 UTC, z00sts commented on migrations/migrations.py
> +    revision = "250c6848576f"
не

2017-08-31 11:24 UTC, z00sts commented
!test

2017-09-01 06:03 UTC, skyline-gleb approved these changes

2017-09-01 06:12 UTC, merged