[WIP] EndpointRemover
2gis/vmmaster pull request #262
Opened 2017-10-12 13:02 UTC by sh0ked

2017-10-13 09:07 UTC, sh0ked commented on vmpool/virtual_machines_pool.py
> +            time.sleep(constants.TIME_OF_SLEEP_AFTER_ATTEMPT)
Есть второй вариант как это реализовать https://github.com/2gis/vmmaster/blob/d0052cbad1b3d2402735f70a123d8c01cd979716/vmpool/virtual_machines_pool.py#L90-L94
Его плюсы:
- не надо использовать эту прекрасную либу-бэкпорт с python3
- есть в twisted, который мы уже используем
Но это вызывает сейчас очень много ошибок при параллельном удалении машин (последовательное удаление - фу!). Ошибки связаны с работой с базой, те самые "объект приаттачен к другой сессии" или "соединение к бд было разорвано". 

С ThreadPoolExecutor работает идеально, параллельно, быстро, без ошибок.

2017-10-13 09:08 UTC, sh0ked commented on vmpool/virtual_machines_pool.py
> +        return self.platforms.get_endpoints(self.id, efilter="wait for service")
да, такие статусы чет не сильно круто.

2017-10-13 09:36 UTC, z00sts commented on vmpool/virtual_machines_pool.py
> +        self.pool.free()
self.pool.free() тут наверное лишний?

2017-10-13 09:46 UTC, sh0ked commented on vmpool/virtual_machines_pool.py
> +        self.pool.free()
Я что-то решил его перенести в EndpointRemover т.к. он один теперь занимается удалением виртуалок и вроде подходящее место при выключении его удалять виртуалки. Хотя может и не стоит так делать.

2017-10-13 09:50 UTC, z00sts commented on vmpool/virtual_machines_pool.py
> +        self.pool.free()
Можно перенести целиком сюда этот метод, а там только дёрнуть его типа `self.remover.remove_all()`

2017-10-16 03:55 UTC, z00sts commented on vmpool/virtual_machines_pool.py
> +            time.sleep(constants.TIME_OF_SLEEP_AFTER_ATTEMPT)
А reactor.callInThread пробовал?
Если там проблемы с использованием обьектов SQLAlchemy, то они общие для любого способа. В любом случае, вызов в другом потоке. Это нормально. Нужно решить эту проблему

2017-10-16 03:58 UTC, sh0ked commented on vmpool/virtual_machines_pool.py
> +            time.sleep(constants.TIME_OF_SLEEP_AFTER_ATTEMPT)
Пробовал все что есть в twisted для работы в thread. Это все одинаково плохо работает. Логичное замечание про общую проблему, но нет, самое смешное, что ни одной проблемы или фейла я не получил пока тестил этот способ.

2017-10-16 04:02 UTC, z00sts commented on vmpool/virtual_machines_pool.py
> +            time.sleep(constants.TIME_OF_SLEEP_AFTER_ATTEMPT)
Я думаю, проблема эта есть и с экзекьютором, просто пока везёт.
Ты тащишь всюда `self.pool.app.app_context()` ради того, чтобы обновить одно поле - надо подумать, как от этого отказаться. Сделать метод в db на худой конец, это не дело...

2017-10-16 04:06 UTC, sh0ked commented on vmpool/virtual_machines_pool.py
> +            time.sleep(constants.TIME_OF_SLEEP_AFTER_ATTEMPT)
Причем здесь app_context? Проблема вообще не в этом, а в работе с сессиями на уровне приложения, у тебя самого в твоем MR происходят такие же ошибки, только в моем MR это вообще еще хуже становится.

2017-10-16 04:20 UTC, z00sts commented on vmpool/virtual_machines_pool.py
> +            time.sleep(constants.TIME_OF_SLEEP_AFTER_ATTEMPT)
Это отдельный пункт, про app_context, это к проблеме использования sqlalchemy в тредах не относится.

2017-10-16 06:25 UTC, sh0ked commented on vmpool/virtual_machines_pool.py
> +            time.sleep(constants.TIME_OF_SLEEP_AFTER_ATTEMPT)
app_context я не тащу, так сейчас устроено сохранение в бд и костылить что-то отдельно как минимум странно в текущем MR.

```
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Users/n.ustinov/work/vmmaster/vmpool/virtual_machines_pool.py", line 91, in run
    endpoint.service_mode_on()
  File "/Users/n.ustinov/work/vmmaster/vmpool/clone.py", line 83, in service_mode_on
    self.set_mode("service")
  File "/Users/n.ustinov/work/vmmaster/vmpool/clone.py", line 93, in set_mode
    self.save()
  File "/Users/n.ustinov/work/vmmaster/core/db/models.py", line 27, in save
    current_app.database.add(self)
  File "/Users/n.ustinov/work/vmmaster/.tox/lib/python2.7/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/Users/n.ustinov/work/vmmaster/.tox/lib/python2.7/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/Users/n.ustinov/work/vmmaster/.tox/lib/python2.7/site-packages/flask/globals.py", line 34, in _find_app
    raise RuntimeError('working outside of application context')
RuntimeError: working outside of application context
```

2017-10-16 06:29 UTC, z00sts commented on vmpool/virtual_machines_pool.py
> +            time.sleep(constants.TIME_OF_SLEEP_AFTER_ATTEMPT)
Его не нужно так использовать! Это было ошибкой когда-то, не нужно продолжать применять эту плохую практику. Нужно сделать два метода у Database и дёрнуть их в потоке когда нужно.

2017-10-16 06:31 UTC, sh0ked commented on vmpool/virtual_machines_pool.py
> +            time.sleep(constants.TIME_OF_SLEEP_AFTER_ATTEMPT)
Разумеется, но это вообще отдельная задача. Эта вещь будет аффектить на вообще все участки в приложении и никак не относится к данной фиче.

2017-10-16 06:37 UTC, z00sts commented on vmpool/virtual_machines_pool.py
> +            time.sleep(constants.TIME_OF_SLEEP_AFTER_ATTEMPT)
Давай замутим, чтобы Удалятор юзал экзекутор вот так:
`with self.executor() as executor:`

Спрячем в инит вот это `ThreadPoolExecutor(max_workers=constants.ENDPOINT_REMOVER_THREADS)`

2017-10-16 08:38 UTC, z00sts commented on vmpool/endpoint.py
> +        self.pool.free()
Вот это предлагаю пока вернуть в завершение VirtualMachinePool, в таком прям виде.

2017-10-16 08:44 UTC, z00sts commented on vmpool/endpoint.py
> +        self.pool.free()
Еще предлагаю выделить явно, какие вещи нужны EndpointRemover: ему не нужен pool, ему нужны а) база б) контекст приложения в) artifact_collector. Это позволит убрать методы про артефакты из VirtualMachinePool и сделать явными зависимости EndpointRemover

2017-10-16 11:50 UTC, sh0ked commented
!test

2017-10-16 12:23 UTC, sh0ked commented
!test

2017-10-16 12:54 UTC, sh0ked commented
!test

2017-10-17 03:54 UTC, sh0ked commented
!test

2017-10-17 06:21 UTC, skyline-gleb commented on vmpool/platforms.py
> +        return self.get_endpoints(self.provider_id, efilter="all")
а теперь `get_endpoints` c обязательным параметром `provider_id` нужен? я глянул по коду, кажется нет и теперь класс `Platforms` рулится исключительно вокруг своего поля `provider_id`

2017-10-17 06:23 UTC, z00sts commented on vmpool/platforms.py
> +        return self.get_endpoints(self.provider_id, efilter="all")
Тут везде пока нужно указывать provider_id, достаем только "свои" endpoints

2017-10-17 06:27 UTC, sh0ked commented on vmpool/platforms.py
> +        return self.get_endpoints(self.provider_id, efilter="all")
provider_id и раньше был и остался, просто его спрятали в platforms

2017-10-17 06:55 UTC, z00sts commented on vmpool/platforms.py
> +        self.provider_id = provider_id
Не вижу смысла заводить этот setter, используется только в одном месте.

2017-10-17 07:57 UTC, z00sts commented on tests/unit/test_vnc_recorder.py
> +            self.app.pool.provider = PropertyMock(id=PropertyMock(return_value=1))
Минор: можно просто `self.app.pool.provider = PropertyMock(id=1)`

2017-10-17 07:58 UTC, z00sts commented on vmpool/clone.py
> +        return self.__str__()
Не стоит

2017-10-17 07:59 UTC, sh0ked commented on vmpool/clone.py
> +        return self.__str__()
Ну так хоть распечатываются нормально объекты, иначе нифига непонятно же

2017-10-17 08:01 UTC, z00sts commented on vmpool/clone.py
> +        return self.__str__()
Где они криво печатаются? Если в format или '%' просунуть? Я думал, он позовет str, если есть...

2017-10-17 08:02 UTC, sh0ked commented on vmpool/clone.py
> +        return self.__str__()
С одиночным норм и str, но если печатать list, то будет кривота и __repr__ для таких случаев, может быть еще какие-то есть

2017-10-17 08:04 UTC, z00sts commented on vmpool/clone.py
> +        return self.__str__()
Ох.. Не знал

2017-10-17 08:05 UTC, skyline-gleb approved these changes

2017-10-17 08:23 UTC, z00sts commented on vmpool/virtual_machines_pool.py
> +        wait_for_service, on_service = self.wait_for_service, self.on_service
Это экономии на символах тоже не понял

2017-10-17 08:42 UTC, z00sts requested changes

2017-10-17 08:42 UTC, z00sts commented on vmpool/endpoint.py
> +        Thread.__init__(self)
Всё же через super нужно дёргать.

2017-10-17 09:11 UTC, sh0ked commented on vmpool/clone.py
> +        return self.__str__()
@z00sts все готово

2017-10-18 05:54 UTC, z00sts approved these changes

2017-10-18 06:04 UTC, merged