[WIP] EndpointCreator
2gis/vmmaster pull request #263
Opened 2017-10-13 11:01 UTC by sh0ked

- Session wait when endpoint_id will set to <int>
- EndpointCreator finds endpoints for session in "waiting" status and set to "preparing" status during finding endpoint.

2017-10-16 03:51 UTC, z00sts commented on vmpool/endpoint.py
> +            time.sleep(constants.EC_TIME_OF_SLEEP_AFTER_ATTEMPT)
А reactor.callInThread пробовал?

2017-10-16 03:52 UTC, z00sts commented on vmpool/endpoint.py
> +            time.sleep(constants.EC_TIME_OF_SLEEP_AFTER_ATTEMPT)
Если там проблемы с использованием обьектов SQLAlchemy, то они общие для любого способа. В любом случае, вызов в другом потоке. Это нормально. Нужно решить эту проблему

2017-10-17 07:01 UTC, sh0ked commented on tests/unit/test_vnc_recorder.py
> -# coding: utf-8
это я перепишу чуток прям в этом MR

2017-10-17 07:01 UTC, sh0ked commented on vmmaster/app.py
> +        self.pool = VirtualMachinesPool(self, getattr(config, "PROVIDER_NAME", None))
нужен self.sessions внутри pool

2017-10-17 07:02 UTC, sh0ked commented on vmpool/endpoint.py
> +def get_endpoint(session_id, platform):
функция полностью перенесена из helpers сюда без изменений

2017-10-17 07:09 UTC, sh0ked commented
!test

2017-10-17 07:59 UTC, z00sts commented on requirements.txt
> +futures==3.1.1
Лишнее

2017-10-17 08:00 UTC, sh0ked commented on requirements.txt
> +futures==3.1.1
забыл запушить

2017-10-18 05:57 UTC, z00sts commented on vmpool/endpoint.py
> +    def __init__(self, sessions, artifact_collector, app):
Пробрасывать app_context-метод вместо всего app (если возможно)

2017-10-18 10:18 UTC, sh0ked commented
!test

2017-10-18 10:41 UTC, z00sts requested changes

2017-10-18 10:41 UTC, z00sts commented on vmpool/endpoint.py
> +                    log.info("Founded endpoint({}) for session {}".format(session.endpoint_id, session))
Вот тут вроде не хватает проверки, что сессию внезапно закрыли и нужно прекращать создавать endpoint. В ситуации, когда на том конце ждали машину и решили перестать ждать и отключились.

2017-10-18 10:59 UTC, skyline-gleb commented on vmpool/endpoint.py
> +            self.artifact_collector.record_screencast(session)
а `session.restore()` не должно делаться в `record_screencast` ?

2017-10-18 10:59 UTC, skyline-gleb commented on vmpool/endpoint.py
> +            self.artifact_collector.record_screencast(session)
и за `set_screencast_started` отвечать тоже коллектор во время старта записи (`record_screencast`)

2017-10-18 11:02 UTC, sh0ked commented on vmpool/endpoint.py
> +            self.artifact_collector.record_screencast(session)
обсуждено

2017-10-18 11:20 UTC, sh0ked commented on vmpool/endpoint.py
> +    def start_screencast(self, session):
@z00sts кстати, сначала обернул это в тред, но потом убрал, потому что screencast сейчас и так дальше в процесс оборачивается. Ну а тут остается включить крыжик и восстановить сессию, вроде не должно много времени занять

2017-10-18 11:41 UTC, z00sts commented on vmpool/endpoint.py
> +                    log.info("Founded endpoint({}) for session {}".format(session.endpoint_id, session))
Обсудили. Пока оставляем так

2017-10-18 11:42 UTC, z00sts approved these changes

2017-10-18 13:10 UTC, merged