[WIP] Rework get_endpoint method
2gis/vmmaster pull request #274
Opened 2017-10-19 09:34 UTC by sh0ked

2017-10-19 13:05 UTC, sh0ked commented
!test

2017-10-19 13:35 UTC, sh0ked commented
!test

2017-10-19 13:47 UTC, sh0ked commented
!test

2017-10-19 13:51 UTC, sh0ked commented
!test

2017-10-20 05:14 UTC, skyline-gleb approved these changes

2017-10-20 05:47 UTC, z00sts commented on tests/unit/test_endpoint_preparer.py
> +        self.assertFalse(session.set_endpoint_id.called)
Не совсем понял, что проверяется в этом тесте. По названию я бы ожидал проверки на то, что машина прекратила готовиться - но он так не умеет.

2017-10-20 05:50 UTC, z00sts commented on tests/unit/test_openstack_clone.py
> +            self.clone.create()
Можно тест переименовать

2017-10-20 05:50 UTC, z00sts commented on tests/unit/test_openstack_clone.py
> +            self.clone.create()
И этот

2017-10-20 05:51 UTC, sh0ked commented on tests/unit/test_endpoint_preparer.py
> +        self.assertFalse(session.set_endpoint_id.called)
Здесь проверяется кейс, когда preparer начал создавать endpoint и сессия была закрыта, мы выходим и проверили, что ничего дальше не создали для этой сессии. Подчистить этот ендпоинт должен remover.

2017-10-20 05:52 UTC, z00sts commented on vmpool/endpoint.py
>          self.lock = Lock()
На самом деле тут почти всё можно приватить, недавно об этом подумал как раз.
Но пока и так ОК :+1:

2017-10-20 05:53 UTC, sh0ked commented on tests/unit/test_endpoint_preparer.py
> +        self.assertFalse(session.set_endpoint_id.called)
Ну и понятно, что это на случай если мы не с первой попытки создали тачку. Если с первой, то в это условие не попадем и просто завершим работу

2017-10-20 05:54 UTC, z00sts commented on vmpool/endpoint.py
> +    def is_running(self):
давай лучше property "running"

2017-10-20 06:18 UTC, z00sts commented on vmpool/endpoint.py
> +                        raise CreationException("Got non-ready endpoint")
```python
if not self.is_running():
    if _endpoint:...
    break
...
if _endpoint:
    ....
    break
else:
    raise

```

2017-10-20 07:56 UTC, sh0ked commented on vmpool/endpoint.py
> +                        raise CreationException("Got non-ready endpoint")
готово

2017-10-20 07:56 UTC, sh0ked commented on vmpool/endpoint.py
> +    def is_running(self):
готово

2017-10-20 07:56 UTC, sh0ked commented on tests/unit/test_openstack_clone.py
> +            self.clone.create()
готово

2017-10-20 07:56 UTC, sh0ked commented on tests/unit/test_openstack_clone.py
> +            self.clone.create()
готово

2017-10-20 07:57 UTC, sh0ked commented
!test

2017-10-20 08:21 UTC, z00sts requested changes

2017-10-20 08:21 UTC, z00sts commented on vmpool/endpoint.py
> +                        session.set_status("preparing")
Этот блок про сессию кажется можно вынести из цикла в начало prepare_endpoint. Иначе это чревато зацикливанием на подготовке. Мы должны один раз её отправить в preparing в начале и дальше уже только поллить её статус.

2017-10-20 08:25 UTC, z00sts commented on vmpool/endpoint.py
> +            if not session.endpoint_id and not session.closed:
А тут мне кажется нужно переводить статус в 'waiting' при условии, что session.is_preparing, а не 'not closed'.

2017-10-20 08:47 UTC, sh0ked commented on vmpool/endpoint.py
> +                        session.set_status("preparing")
было раньше вверху, но я перенес потому что это вызовет проблему если мы сменили статус на preparing, а потом наткнулись на закрытую сессию, например, то статус так и останется в preparing. Но если учесть нижнее замечание, то может быть имеет смысл так сделать

2017-10-20 08:47 UTC, sh0ked commented on vmpool/endpoint.py
> +            if not session.endpoint_id and not session.closed:
выше написал

2017-10-20 08:56 UTC, sh0ked commented
!test

2017-10-20 08:58 UTC, z00sts approved these changes

2017-10-20 09:16 UTC, merged