Endpoints view in API
2gis/vmmaster pull request #292
Opened 2017-11-02 09:49 UTC by sh0ked

2017-11-06 10:25 UTC, z00sts requested changes

2017-11-06 10:25 UTC, z00sts commented on core/db/__init__.py
> +                        endpoints[endpoint_type][endpoint_dict_property] += endpoint_dict_value
Давай сначала достанем все endpoints для текущих активных провайдеров в список и следующими шагами из этого списка выпарсим всё по типам 'using'. 'pool' и т.д. и соберем в результирующий dict. Как сейчас - читается жутко

2017-11-07 11:25 UTC, z00sts approved these changes

2017-11-08 03:18 UTC, skyline-gleb approved these changes

2017-11-08 03:53 UTC, sh0ked commented
!test

2017-11-08 04:36 UTC, sh0ked commented
boom

2017-11-08 04:36 UTC, merged