User environment variables from dc
2gis/vmmaster pull request #313
Opened 2017-11-24 08:56 UTC by sh0ked

- return ondemand endpoint **always** if got environment_variables from User's DesiredCaps
- environment_variables property for Endpoint Model
- set common EnvironmentVariables for ondemand or preloaded endpoints and configuring in config.py

2017-11-24 08:56 UTC, sh0ked commented
!test

2017-11-24 09:29 UTC, sh0ked commented
!test

2017-11-24 10:02 UTC, sh0ked commented on tests/functional/functional_tests.py
> +        if ":" not in platform:
не придумал как в условиях изменяющихся названий докер-образов выбирать нужный, в опенстеке-то уж точно с : нет ничего

2017-11-24 10:07 UTC, sh0ked commented
!test

2017-11-24 10:29 UTC, sh0ked commented
!test

2017-11-27 04:19 UTC, skyline-gleb approved these changes

2017-11-27 05:03 UTC, z00sts commented on vmpool/virtual_machines_pool.py
> +        if not env_vars and endpoint:
Тут можно не дёргать self.get_by_platform, если нет env_vars, а не пост-фактум проверять. Кажется, так лучше будет.

2017-11-27 05:47 UTC, z00sts approved these changes

2017-11-27 13:33 UTC, sh0ked commented on vmpool/virtual_machines_pool.py
> +        if not env_vars and endpoint:
Ты про такой вариант? Не очень же. Если нет в пуле, то надо создавать же.
```
    def get_vm(self, platform_name, dc):
        timer = profiler.functions_duration_manual(self.get_vm.__name__)
        env_vars = get_environment_variables_from_dc(dc)

        if not env_vars:
            endpoint = self.get_by_platform(platform_name)
            if endpoint:
                timer.end()
                return endpoint

        endpoint = self.add(platform_name, environment_variables=env_vars)

        if endpoint and getattr(endpoint, "ready", False):
            timer.end()
            return endpoint
```

2017-11-28 03:47 UTC, z00sts commented on vmpool/virtual_machines_pool.py
> +        if not env_vars and endpoint:
Да, я про этот вариант. Всё правильно, если нет в пуле - он пойдет создавать же.

2017-11-28 04:55 UTC, z00sts commented on vmpool/virtual_machines_pool.py
> +        if not env_vars and endpoint:
Ченджес реквестед

2017-11-28 04:55 UTC, z00sts requested changes

2017-11-28 04:55 UTC, z00sts commented on vmpool/virtual_machines_pool.py
> +        if not env_vars and endpoint:
Реквест ченджес

2017-11-28 05:40 UTC, sh0ked commented
!test

2017-11-28 06:03 UTC, sh0ked commented on vmpool/virtual_machines_pool.py
> +        if not env_vars and endpoint:
гэтово

2017-11-28 06:21 UTC, z00sts approved these changes

2017-11-28 12:27 UTC, merged