[WIP] Fix user response after no response from endpoint
2gis/vmmaster pull request #314
Opened 2017-11-27 13:11 UTC by sh0ked

- избавился от двойственности ответов клиенту (selenium_error_response и form_response)
- если отвалились по таймауту запроса в эндпоинт, то не валим всю сессию, а формируем ответ и отправляем пользователю
- скриншоты на предыдущий пункт теперь делаются автоматом, как и задумано ранее, лишний вызов take_screenshot убрал
- при эксепшн в make_request не срабатывал swap_session обратно на нормальный id сессии, теперь это исправлено
- добавлен Content-Type как описано в доке Json Wire Protocol

2017-11-27 13:11 UTC, sh0ked commented
!test

2017-11-28 03:50 UTC, z00sts requested changes

2017-11-28 03:50 UTC, z00sts commented on core/db/models.py
> -            raise e
Тут что-то много ты удалил: в случае, если endpoint не пингуется мы всё таки должны поднимать EndpointUnreachableError и валить сессию.

2017-11-28 06:08 UTC, sh0ked commented
!test

2017-11-28 06:21 UTC, sh0ked commented on core/db/models.py
> -            raise e
done

2017-11-28 06:22 UTC, sh0ked commented on core/db/models.py
> -            raise e
вынес в transparent и будет пинговать в случае 500 ответа на реквест, либо None - когда был raise

2017-11-28 06:38 UTC, z00sts approved these changes

2017-11-28 07:42 UTC, skyline-gleb approved these changes

2017-11-28 09:48 UTC, sh0ked commented on tests/functional/app/views.py
> +    return render_template('index.html', title='Long Request', user={})
для теста на RequestTimeoutException

2017-11-28 09:53 UTC, sh0ked commented on vmmaster/webdriver/helpers.py
> +        swap_session(request, str(request.session.id))
отказался от прошлого в сторону такого решения потому, что make_request в предыдущем варианте начинал возвращать еще больше разных по типу результатов, еще в текущем варианте красивше выглядит проверка, что не доступен эндпоинт для конкретного типа ошибки

2017-11-28 09:54 UTC, sh0ked commented
!test

2017-11-28 09:54 UTC, z00sts commented on vmmaster/webdriver/helpers.py
> +        swap_session(request, str(request.session.id))
круто

2017-11-28 09:56 UTC, sh0ked commented on tests/functional/tests/test_normal.py
> +        self.driver.get("{}/long".format(self.micro_app_addr))
кстати, выполняется первым и гарантирует, что следом идущие тесты пройдут

2017-11-28 10:16 UTC, sh0ked commented
!test

2017-11-28 10:57 UTC, sh0ked commented
!test

2017-11-28 11:18 UTC, sh0ked commented
!test

2017-11-28 11:19 UTC, sh0ked commented
!test

2017-11-28 11:55 UTC, sh0ked commented
!test

2017-11-28 12:03 UTC, sh0ked commented
!test

2017-11-28 12:28 UTC, merged